#!/bin/sh
# chkconfig: 345 99 10
# description: Oracle auto start-stop script.
#
# Change the value of ORACLE_HOME to specify the correct Oracle home
# directory for your installation.

ORACLE_HOME=/u02/app/oracle/product/oas/10.1.2

#
# Change the value of ORACLE to the login name of the
# oracle owner at your site.
#

ORACLE=oracle
PATH=${PATH}:$ORACLE_HOME/bin
export ORACLE_HOME PATH ORACLE_HOME_LISTNER

#
case $1 in
'start')
        su - oracle -c "$ORACLE_HOME/opmn/bin/opmnctl startall"
        touch /var/lock/subsys/oas
        ;;
'stop')
        su - oracle -c "$ORACLE_HOME/opmn/bin/opmnctl shutdown"
        rm -f /var/lock/subsys/oas
        ;;
'status')
        exit 1
        ;;
*)
        echo "usage: $0 {start|stop}"
        exit
        ;;
esac
#
exit

